import type { HarnessConfiguration } from '../config/configuration.js'

/** Generates a trusted overlay from validated VS Code settings. */
export function renderOverlay(configuration: HarnessConfiguration): string {
  const thinking = configuration.reasoningEffort === 'off' ? 'disabled' : 'enabled'
  return `# Generated by DeepSeek Harness for VS Code. Manual edits are overwritten.\n\
- id: llm-deepseek\n\
  config:\n\
    thinking: ${thinking}\n\
    reasoningEffort: ${configuration.reasoningEffort}\n\
\n\
- id: agent-default-model\n\
  config:\n\
    provider: ${JSON.stringify(configuration.provider)}\n\
    model: ${configuration.model}\n\
\n\
- id: agent-presets\n\
  config:\n\
    default: ${configuration.agentPreset}\n\
\n\
- id: permission\n\
  config:\n\
    # Patch rows replace their complete config, so restate every shipped preset.\n\
    presets:\n\
      read-only:\n\
        sandbox: read-only\n\
        approval: ask\n\
        name: Read only\n\
        description: Prevent file writes while keeping approval prompts enabled.\n\
      workspace-write:\n\
        sandbox: workspace-write\n\
        approval: ask\n\
        name: Workspace write\n\
        description: Allow workspace and temporary-directory writes with approval for wider access.\n\
      danger-full-access:\n\
        sandbox: danger-full-access\n\
        approval: never\n\
        name: Full access\n\
        description: Allow unrestricted file writes without approval prompts.\n\
    defaultPreset: ${configuration.permissionMode}\n`
}
